/**
 * bundle-migrations.ts
 *
 * Reads all .sql files from src/db/migrations/ in sorted order and generates
 * src/db/migrations.generated.ts, which inlines them as string constants.
 *
 * Run as part of the build step so that the compiled binary doesn't need to
 * access the filesystem to find migration files.
 */

import fs from 'node:fs';
import path from 'node:path';

const migrationsDir = path.join(import.meta.dir, '../src/db/migrations');
const outFile       = path.join(import.meta.dir, '../src/db/migrations.generated.ts');

const files = fs
  .readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort();

const entries = files.map((file) => {
  const sql = fs.readFileSync(path.join(migrationsDir, file), 'utf8');
  return `  { name: ${JSON.stringify(file)}, sql: ${JSON.stringify(sql)} }`;
});

const output = `// AUTO-GENERATED by scripts/bundle-migrations.ts — do not edit by hand.
// Re-run \`bun run build\` (or \`bun scripts/bundle-migrations.ts\`) to update.

export type Migration = { name: string; sql: string };

export const migrations: Migration[] = [
${entries.join(',\n')},
];
`;

fs.writeFileSync(outFile, output, 'utf8');
console.log(`[bundle-migrations] wrote ${files.length} migration(s) to src/db/migrations.generated.ts`);
